### ISSUE TITLE
Chatsound's Autocomplete stays open if chat is closed by the close button

### ISSUE THREAD

**Issue by Techbot121** [PAC3-Server/EasyChat#3]
![image](https://user-images.githubusercontent.com/3000604/26938102-89c2a470-4c73-11e7-8295-9ec23542bb56.png)

it properly closes when you press enter.

**Comment by Earu** [comment]
I think I know why, the chatbox doesnt get deleted when you press close or enter or esc, its set to invisible, and yeah chatsounds think you're still typing or something

**Comment by Earu** [comment]
Fixed.
