### ISSUE TITLE
Saying *dead* while being alive

### ISSUE THREAD

**Issue by Datamats** [PAC3-Server/EasyChat#4]
Both me and @Techbot121 is getting *dead* in front us on my client even as neither of us are dead
https://i.imgur.com/K1lkkVW.png

**Comment by Techbot121** [comment]
seems to be fixed now

**Comment by LuaTenshi** [comment]
Yeah I fixed it in a commit earlier this morning.

**Comment by Techbot121** [comment]
no it was @Earu with fa9c965
